
import Header from "@/components/Header";
import Hero from "@/components/Hero";

import About from "@/components/About";
import Services from "@/components/Services";
import DigitalGrowthFramework from "@/components/DigitalGrowthFramework";
import Challenges from "@/components/Challenges";
import Industries from "@/components/Industries";
import Process from "@/components/Process";
import WhyUs from "@/components/WhyUs";
import RecentBlogs from "@/components/RecentBlogs";
import SEOContent from "@/components/SEOContent";
import CTA from "@/components/CTA";
import Footer from "@/components/Footer";
import WhatsAppButton from "@/components/WhatsAppButton";

// Export metadata for Google & Bing search engine optimization + OpenGraph Social cards
export const metadata = {
  keywords: [
   "Best Digital Marketing Agency",
  "Digital Marketing Company",
  "Online Marketing Services",
  "Digital Marketing Experts",
  "Internet Marketing Agency",
  "Performance Marketing Agency",
  "Best Digital Marketing Agency in India",
  "Affordable Digital Marketing Services",
  "ROI Driven Digital Marketing Agency",
  "End-to-End Digital Marketing Solutions",
  "Digital Marketing Company for Startups",
  "Online Marketing Agency for Business Growth",
  "Full Service Digital Marketing Company",
  "Data Driven Digital Marketing Agency",
  "Lead Generation Digital Marketing Experts",
  "Custom Digital Marketing Solutions",
  "Digital Marketing Services That Drive Sales",
  "Digital Marketing Agency for Brand Growth",
  "Digital Marketing Partner for Businesses",
  "Trusted Online Marketing Experts",
  "Digital Marketing Agency for Small Businesses",
  "Digital Marketing Company That Generates Quality Leads",
  "Affordable Digital Marketing Services for Small Businesses",
  "Affordable Digital Marketing Services Near Me",
  "Online Marketing Agency for Startup Businesses",
  "Digital Marketing Experts for Business Growth",
  "Improve Business with Digital Marketing Services",
  "Digital Marketing Agency with Proven Results",
  "Complete Digital Marketing Solutions for Companies",
  "Digital Marketing Company for Local Businesses",
  "Internet Marketing Services for Business Owners",
  "Performance Marketing Agency for Lead Generation",
  "Hire Digital Marketing Experts for My Business",
  "Increase Website Traffic with Digital Marketing",
  "Digital Marketing Agency for Service-Based Businesses",
  "Digital Marketing Company with Affordable Packages",
  "Online Branding Services for Small Businesses",
  "Digital Marketing Consultants Near Me",
  "Best Marketing Company for Startups",
  "Digital Marketing Company with SEO Experts",
  "Digital Growth Partner for Businesses",
  "Business Growth Through Digital Marketing",
  "Results Driven Digital Marketing Agency",
  "SEO and Digital Marketing Company",
  "Digital Advertising Agency",
  "Business Growth Marketing Agency",
  "Digital Branding Services",
  "Lead Generation Marketing Agency",
  "Digital Marketing Strategy Experts",
  "Business Marketing Solutions",

  "Best Digital Marketing Agency in India",
    "Affordable Digital Marketing Services for Small Businesses",
    "ROI Driven Digital Marketing Agency",
    "End-to-End Digital Marketing Solutions",
    "Digital Marketing Company for Startups",
    "Online Marketing Agency for Business Growth",
    "Full Service Digital Marketing Company",
    "Data Driven Digital Marketing Agency",
    "Lead Generation Digital Marketing Experts",
    "Custom Digital Marketing Solutions",
    "Digital Marketing Services That Drive Sales",
    "Digital Marketing Agency for Brand Growth",
    "Digital Marketing Partner for Businesses",
    "Trusted Online Marketing Experts",
    "Business Growth Through Digital Marketing",
    "best digital marketing agency for small businesses",
    "digital marketing company that generates quality leads",
    "affordable digital marketing services near me",
    "online marketing agency for startup businesses",
    "digital marketing experts for business growth",
    "improve business with digital marketing services",
    "digital marketing agency with proven results",
    "complete digital marketing solutions for companies",
    "digital marketing company for local businesses",
    "internet marketing services for business owners",
    "performance marketing agency for lead generation",
    "hire digital marketing experts for my business",
    "increase website traffic with digital marketing",
    "digital marketing agency for service-based businesses",
    "digital marketing company with affordable packages",
    "online branding services for small businesses",
    "digital marketing consultants near me",
    "best marketing company for startups",
    "digital marketing company with SEO experts",
    "digital growth partner for businesses",
    "Best GEO Agency",
    "LLM SEO Services",
    "GEO Services India",
    "LLM Indexing Optimization",
    "AI Citation Optimization Services",
    "LLM Visibility Strategy",
    "AI Search Optimization Services",
    "Generative Engine Optimization (GEO)",
    "Answer Engine Optimization (AEO)",
    "LLM SEO Consulting",
    "AI Search Visibility Services",
    "ChatGPT Optimization Services",
    "Google AI Overviews Optimization",
    "Perplexity AI Optimization",
    "Microsoft Copilot Optimization",
    "Gemini AI Optimization",
    "Claude AI Optimization",
    "AI Citation Building",
    "AI Search Readiness Audit",
    "Entity SEO Services",
    "Knowledge Graph Optimization",
    "llms.txt Setup Service",
    "AI Crawler Optimization",
    "GPTBot Optimization",
    "Google-Extended Configuration",
    "Structured Data for AI Search",
    "AI Content Strategy",
    "AI Brand Authority Development",
    "AI Search Performance Monitoring",
    "AI Visibility Consulting",
    "AI Indexability Audit",
    "Digital Marketing TenX AEO services",
    "TenX AI-powered digital marketing agency",
    "Digital Marketing TenX GEO services",
    "Digital Marketing TenX reviews",
    "Digital Marketing TenX AI search optimization",
    "Digital Marketing TenX AI marketing agency Telangana",
    "Digital Marketing TenX ChatGPT optimization",
    "TenX GEO and AEO company Hyderabad",
    "TenX Hyderabad AEO agency",
    "Digital Marketing TenX AI search visibility partner",
    "TenX digital marketing AI search",
    "TenX 10X digital marketing AEO",
    "Digital Marketing TenX Begumpet",
    "Digital Marketing TenX certified Google partner AEO",
    "Digital Marketing TenX Gumidelli Towers",
    "TenX AI marketing consultancy Hyderabad",
    "Digital Marketing TenX Hyderabad SEO and AEO",
    "SEO agency offering AEO services Hyderabad",
    "on-page SEO for AI search visibility",
    "SEO and AI search optimization company",
    "off-page SEO for AI citation building",
    "technical SEO with AEO integration",
    "content optimization for SEO and AI search",
    "local SEO and AEO combined services",
    "keyword research for SEO and AEO",
    "SEO company with GEO expertise",
    "Google Ads agency with AI search strategy",
    "Google Ads and GEO combined strategy",
    "PPC management with AEO alignment",
    "paid search and AI search integration company",
    "performance marketing and AI visibility agency",
    "AI search ready website design agency",
    "conversion-optimized website design for AI search",
    "website development for AEO and GEO",
    "Next.js website design for AI crawlability",
    "schema-ready website design company",
    "social media marketing with AI search strategy",
    "social content strategy for AI citation building",
    "LinkedIn content strategy for Copilot visibility",
    "brand authority building through social media for AI search",
    "e-commerce SEO with GEO strategy",
    "e-commerce content strategy for AI citation",
    "Shopify store optimization for AI search",
    "WooCommerce AI search optimization agency",
    "product page schema for AI shopping search",
    "WhatsApp automation with AI-driven lead qualification",
    "conversational AI marketing services Hyderabad",
    "AI-powered WhatsApp marketing agency",
    "WhatsApp API automation for AI-search-driven leads",
    "AEO agency in Hyderabad",
    "AEO agency in Kakinada",
    "GEO services in Hyderabad",
    "GEO services in Kakinada",
    "AI search optimization company Hyderabad",
    "AI search optimization company Kakinada",
    "AEO agency in Secunderabad",
    "AEO agency in Rajahmundry",
    "GEO services in Secunderabad",
    "GEO services in Rajahmundry",
    "AI search optimization company Secunderabad",
    "AI search optimization company Rajahmundry",
    "AEO agency in Begumpet",
    "AEO agency in Vijayawada",
    "GEO services in Begumpet",
    "GEO services in Vijayawada",
    "AI search optimization company Begumpet",
    "AI search optimization company Vijayawada",
    "AEO agency in Gachibowli",
    "AEO agency in Guntur",
    "GEO services in Gachibowli",
    "GEO services in Guntur",
    "AI search optimization company Gachibowli",
    "AI search optimization company Guntur",
    "AEO agency in Kukatpally",
    "AEO agency in Tenali",
    "GEO services in Kukatpally",
    "GEO services in Tenali",
    "AI search optimization company Kukatpally",
    "AI search optimization company Tenali",
    "AEO agency in Warangal",
    "AEO agency in Nellore",
    "GEO services in Warangal",
    "GEO services in Nellore",
    "AI search optimization company Warangal",
    "AI search optimization company Nellore",
    "AEO agency in Karimnagar",
    "AEO agency in Kurnool",
    "GEO services in Karimnagar",
    "GEO services in Kurnool",
    "AI search optimization company Karimnagar",
    "AI search optimization company Kurnool",
    "AEO agency in Nizamabad",
    "AEO agency in Nandyal",
    "GEO services in Nizamabad",
    "GEO services in Nandyal",
    "AI search optimization company Nizamabad",
    "AI search optimization company Nandyal",
    "AEO agency in Khammam",
    "AEO agency in Anantapur",
    "GEO services in Khammam",
    "GEO services in Anantapur",
    "AI search optimization company Khammam",
    "AI search optimization company Anantapur",
    "AEO agency in Nalgonda",
    "AEO agency in Tirupati",
    "GEO services in Nalgonda",
    "GEO services in Tirupati",
    "AI search optimization company Nalgonda",
    "AI search optimization company Tirupati",
    "AEO agency in Visakhapatnam",
    "AEO agency in Kadapa",
    "GEO services in Visakhapatnam",
    "GEO services in Kadapa",
    "AI search optimization company Visakhapatnam",
    "AI search optimization company Kadapa",
    "AEO agency in Vizianagaram",
    "AEO agency in Ongole",
    "GEO services in Vizianagaram",
    "GEO services in Ongole",
    "AI search optimization company Vizianagaram",
    "AI search optimization company Ongole",
    "AEO agency Telangana",
    "GEO services Rayalaseema region",
    "GEO company Telangana",
    "AI search optimization Rayalaseema",
    "AI search optimization Telangana",
    "best AEO agency in AP and Telangana",
    "AEO agency Andhra Pradesh",
    "GEO consultant AP and TG",
    "GEO company Andhra Pradesh",
    "AI search marketing agency South India",
    "AI search optimization Andhra Pradesh",
    "digital marketing agency AP and TG with AEO expertise",
    "AEO agency Rayalaseema",
    "AI search visibility agency Telangana and Andhra Pradesh",
    "AEO for Real Estate businesses",
    "AI search optimization for Construction companies",
    "GEO services for Real Estate brands",
    "AEO for Technology / SaaS businesses",
    "AI search optimization for Real Estate companies",
    "GEO services for Technology / SaaS brands",
    "AEO for Healthcare businesses",
    "AI search optimization for Technology / SaaS companies",
    "GEO services for Healthcare brands",
    "AEO for Finance businesses",
    "AI search optimization for Healthcare companies",
    "GEO services for Finance brands",
    "AEO for Education businesses",
    "AI search optimization for Finance companies",
    "GEO services for Education brands",
    "AEO for E-Commerce businesses",
    "AI search optimization for Education companies",
    "GEO services for E-Commerce brands",
    "AEO for Retail businesses",
    "AI search optimization for E-Commerce companies",
    "GEO services for Retail brands",
    "AEO for Manufacturing businesses",
    "AI search optimization for Retail companies",
    "GEO services for Manufacturing brands",
    "AEO for Restaurants businesses",
    "AI search optimization for Manufacturing companies",
    "GEO services for Restaurants brands",
    "AEO for Local Services businesses",
    "AI search optimization for Restaurants companies",
    "GEO services for Local Services brands",
    "AEO for Construction businesses",
    "AI search optimization for Local Services companies",
    "GEO services for Construction brands",
    "how to rank in AI search results 2026",
    "how to add FAQ schema for AI search",
    "how to get cited by ChatGPT",
    "how to build topical authority for AI search",
    "how to appear in Google AI Overviews",
    "can SEO agencies do AEO and GEO together",
    "how to optimize content for Perplexity AI",
    "do I need a separate AEO agency",
    "what is answer engine optimization",
    "how to future-proof my SEO strategy for AI search",
    "what is generative engine optimization",
    "how does generative engine optimization work",
    "how much does AEO services cost in India",
    "is AEO the same as traditional SEO",
    "how much does GEO services cost in Hyderabad",
    "how to check if my brand appears in ChatGPT answers",
    "best AEO agency near me",
    "why is my business not showing up in ChatGPT",
    "best GEO company near me",
    "how to write content that AI engines cite",
    "how to increase AI search visibility for my business",
    "how long does AEO take to show results",
    "how to track ChatGPT citations for my website",
    "what is the difference between AEO and GEO",
    "how to make my website AI search friendly",
    "affordable AEO services Hyderabad",
    "AEO service pricing India",
    "AEO packages for small businesses Hyderabad",
    "GEO service pricing Hyderabad",
    "monthly GEO packages India",
    "AI search optimization retainer packages",
    "AEO audit service Hyderabad",
    "custom AEO strategy for business",
    "free AI search visibility audit",
    "book free AEO consultation",
    "GEO consultation Hyderabad",
    "request AI search visibility audit",
    "hire AEO expert Hyderabad",
    "AEO agency for startups Hyderabad",
    "hire GEO consultant Telangana",
    "GEO services for enterprise brands India",
    "AI in digital marketing 2026 playbook",
    "step-by-step FAQ schema guide",
    "answer engine optimization guide for Hyderabad businesses",
    "AEO checklist for small businesses",
    "generative engine optimization guide for Indian businesses",
    "GEO checklist for e-commerce brands",
    "local AEO guide for Telangana businesses",
    "case study AEO results Hyderabad business",
    "local GEO guide for Andhra Pradesh businesses",
    "case study GEO results Indian brand",
    "how to improve website SEO for AI search 2026",
    "AI search statistics 2026 India",
    "Google Ads vs Facebook Ads for AI-search-era lead generation",
    "future of search AI trends 2027",
    "ChatGPT search vs Google search for businesses",
    "why AEO matters for Hyderabad startups",
    "Best Digital Marketing Agency in Hyderabad",
    "Digital Marketing Agency in Hyderabad",
    "Digital Marketing Company in Hyderabad",
    "Top Digital Marketing Company in Hyderabad",
    "Top Digital Marketing Agencies in Hyderabad",
    "Best Digital Marketing Company in Hyderabad",
    "Best Digital Marketing Services in Hyderabad",
    "Digital Marketing Services in Hyderabad",
    "Professional Digital Marketing Services Hyderabad",
    "Leading Digital Marketing Company in Hyderabad",
    "Top-Rated Digital Marketing Agency Hyderabad",
    "Digital Marketing Experts in Hyderabad",
    "Top 10 Digital Marketing Agency in Hyderabad"
],

  title: "Best Digital Marketing Agency in Hyderabad | Digital TenX",
  description: "Looking for a results-driven digital marketing agency in Hyderabad? Get SEO, Google Ads & social media marketing that grows leads. Book a free audit today.",
  alternates: {
    canonical: "https://digitalmarketingtenx.com",
  },
  openGraph: {
    title: "Best Digital Marketing Agency in Hyderabad | Digital TenX",
    description: "Looking for a results-driven digital marketing agency in Hyderabad? Get SEO, Google Ads & social media marketing that grows leads. Book a free audit today.",
    url: "https://digitalmarketingtenx.com",
    type: "website",
    images: [
      {
        url: "https://digitalmarketingtenx.com/og-image.webp",
        width: 1200,
        height: 630,
        alt: "Digital Marketing TenX Agency Hyderabad",
      },
    ],
  },
};

import { PageSchema } from "@/components/schema/SchemaComponents";

export default function Home() {
  return (
    <>
      <PageSchema 
        title={metadata.title} 
        description={metadata.description}
        url="/" 
      />
      <Header />
      <main>
        <Hero />
        <About />
        <Services />
        <DigitalGrowthFramework />
        <WhyUs />
        <Challenges />
        <Industries />
        <Process />
        <RecentBlogs />
        <SEOContent />
        <CTA />
      </main>
      <Footer />
      <WhatsAppButton />
    </>
  );
}
