export const metadata = {
  keywords: [
    "Website Design Company",
    "Website Development",
    "Web Design Services",
    "Custom Website Design",
    "Business Website Development",
    "Professional Website Design Company",
    "Responsive Website Design Services",
    "Custom Website Development Company",
    "Business Website Design Services",
    "SEO Friendly Website Design",
    "Affordable Website Development",
    "Modern Website Design Agency",
    "Website Development Company in India",

    "Professional Website Design Company",
    "SEO Friendly Website Development",
    "Responsive Business Website Design",
    "Affordable Website Design Services",
    "Custom Website Development Company",
    "Mobile Friendly Website Designers",
    "Corporate Website Development Services",
    "Website Design for Small Businesses",
    "Modern Business Website Development",
    "Fast Loading Website Design Services",
    "UI UX Website Design Company",
    "Website Redesign Services",
    "Business Website Development Experts",
    "Website Design and Development Company in Hyderabad",
    "Website Designing Services in Hyderabad",
    "Web Design Company in Hyderabad",
    "Responsive Web Design Company in Hyderabad",
    "Website Design Agency in Hyderabad",
    "Web Design Services in Hyderabad",
    "Professional Website Designers in Hyderabad",
    "Affordable Website Design Company in Hyderabad",
    "Creative Web Design Agency in Hyderabad",
    "Web Design and Development Company in Hyderabad",
    "Best Website Designing Company in Hyderabad",
    "Top Web Designing Company in Hyderabad",
    "Website Developers in Hyderabad",
    "Website Designers in Begumpet, Hyderabad",
    "Top Rated Web Designing Company in Hyderabad",
    "Best Website Development Services in Hyderabad",
    "Website Development in Hyderabad",
    "Website Development Near Me",
    "Top Web Development Company in Hyderabad",
    "Web Development Services in Hyderabad",
    "AI Powered Web Development Company in Hyderabad",
    "Best Web Development Company in Hyderabad",
    "Top Web Development Services in Hyderabad",
    "Website Design and Development Services in Hyderabad",
    "Top Website Development Companies in Hyderabad",
    "Website Development Company in Hyderabad",
    "Web Development Companies in Hyderabad",
    "WordPress Website Development in Hyderabad",
    "WordPress Website Development Company in Hyderabad",
    "Best WordPress Development Company in Hyderabad",
    "CMS Website Development Services in Hyderabad",
    "Top WordPress Development Company in Hyderabad",
    "Professional WordPress Developers in Hyderabad",
    "Affordable WordPress Website Development in Hyderabad",
    "Custom WordPress Website Design Company in Hyderabad",
    "WordPress Website Design and Development in Hyderabad"
],

  title: "Website Design and Development Company in Hyderabad | TenX",
  description: "Looking for a website design and development company in Hyderabad? Get SEO-friendly, responsive websites from Digital Marketing TenX. Contact us today!",
  alternates: {
    canonical: "https://digitalmarketingtenx.com/services/website-design"
  }
};

export default function Layout({ children }) {
  return children;
}
